In [1]:
print("xys")

xys


In [3]:
print("hi")
print("how are you")

hi
how are you


In [5]:
#Variable and assignments
x=34

In [6]:
x = 34
y = 45

type(x)
a,b = 20,30
a+b

50

In [8]:
id(x)

2206111264080

In [9]:
x

34

In [10]:
float(x)

34.0

In [11]:
str(x)

'34'

In [16]:
#A tuple is a one-dimensional, immutable ordered sequence of items which can be of mixed data types
first_tuple = (12, "Jack", 45.6, 'new', (3,2), 'test')
first_tuple[1]


'Jack'

In [13]:
first_tuple

(12, 'Jack', 45.6, 'new', (3, 2), 'test')

In [ ]:
#Lists


In [23]:
l2 = [21,51,80,92,72,100]
print(l2)
l3 = sorted(l2)
print(l3)

[21, 51, 80, 92, 72, 100]
[21, 51, 72, 80, 92, 100]


In [24]:
# Conditional statement

marks = 100

if marks >=40:
    print("pass")
else:
    print("Fail")

pass


In [26]:
#Numerical Python (Numbpy) supports multidimensional arrays over which you can easily apply mathmatical operations.

dist = [ 44, 85,90,100]
time = [.02, .05,.06,1.08]

import numpy as np

np_distance = np.array(dist)
np_time = np.array(time)
speed=np_distance/np_time

speed 

array([2200.        , 1700.        , 1500.        ,   92.59259259])

In [28]:
np_distance.shape

(4,)

In [29]:
np_distance.size

4

In [30]:
import numpy as np
a = np.arange(15).reshape(3, 5)
a


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [31]:
a.shape

(3, 5)

In [32]:
a.itemsize

4

In [33]:
type(a)

numpy.ndarray

In [34]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

number_unique = np.unique(a)
number_unique

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [35]:
import pandas as pd

s1=pd.Series(["PYthon", "R", "Scala", "Matlab"])
s1

In [40]:
s1=pd.Series(["PYthon", "R", "Scala", "Matlab"])
s1

0    PYthon
1         R
2     Scala
3    Matlab
dtype: object